groups:
- name: alert.rules
  rules:
    - alert: Node_High_CPUUsage
      expr: (100 - (avg by (instance) (irate(node_cpu_seconds_total{job="node",mode="idle"}[1m])) * 100)) > 75
      for: 1m
      labels:
        severity: warning
      annotations:
        summary: " {{$labels.instance}}:  High CPU usage detected"
        description: " {{$labels.instance}}:  CPU usage is above 75% (current value is:  {{ $value }} )"

      # Defines Alert rule for high CPU load average
    - alert: Node_High_LoadAverage
      expr: ((node_load5 / count without (cpu, mode) (node_cpu_seconds_total{mode="system"})) > 1.1)
      for: 1m
      labels:
        severity: warning
      annotations:
        summary: " {{$labels.instance}}:  High Load Average detected"
        description: " {{$labels.instance}}:  Load Average is high"

    # Defines Alert rule for high swap data usage, indicated by a defined threshold
    - alert: Node_High_SwapUsage
      expr: (((node_memory_SwapTotal_bytes-node_memory_SwapFree_bytes)/node_memory_SwapTotal_bytes)*100) > 50
      for: 1m
      labels:
        severity: warning
      annotations:
        summary: " {{$labels.instance}}:  Swap usage detected"
        description: " {{$labels.instance}}:  Swap usage usage is above 50% (current value is:  {{ $value }} )"

    # Defines Alert rule for High memory usage, indicated by a defined threshold
    - alert: Node_High_MemoryUsage
      expr: (((node_memory_MemTotal_bytes-node_memory_MemFree_bytes-node_memory_Cached_bytes)/(node_memory_MemTotal_bytes)*100)) > 90
      for: 1m
      labels:
        severity: warning
      annotations:
        summary: " {{$labels.instance}}:  High memory usage detected"
        description: " {{$labels.instance}}:  Memory usage is above 90% (current value is:  {{ $value }} )"
