global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
rule_files:
  - "alert_rules.yml"
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - 172.31.26.79:9093
scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 1m
    static_configs:
    - targets: ["172.31.26.79:9090"]

  - job_name: "node"
    static_configs:
    - targets: ["172.31.26.79:9100", "172.31.17.36:9100"]
